# Generated by Django 4.0.5 on 2022-06-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='rostered',
        ),
        migrations.AlterField(
            model_name='roster',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='roster',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
